spring:
  application:
    name: Mulciber
  datasource:
    url: jdbc:postgresql://${db.addr}
    username: ${db.user}
    password: ${db.pass}

---

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5432/mulciber
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop